{
  "name": "8ball",
  "permissions": "NONE",
  "restriction": "4",
  "_id": "wTZwC",
  "actions": [
    {
      "info": "1",
      "infoIndex": "1",
      "storage": "1",
      "varName": "question",
      "name": "Store Command Params"
    },
    {
      "storage": "1",
      "varName": "answer",
      "min": "1",
      "max": "20",
      "name": "Generate Random Number"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "1",
      "iftrue": "2",
      "iftrueVal": "23",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "2",
      "iftrue": "2",
      "iftrueVal": "27",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "3",
      "iftrue": "2",
      "iftrueVal": "31",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "4",
      "iftrue": "2",
      "iftrueVal": "35",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "5",
      "iftrue": "2",
      "iftrueVal": "39",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "6",
      "iftrue": "2",
      "iftrueVal": "43",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "7",
      "iftrue": "2",
      "iftrueVal": "47",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "8",
      "iftrue": "2",
      "iftrueVal": "51",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "9",
      "iftrue": "2",
      "iftrueVal": "55",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "10",
      "iftrue": "2",
      "iftrueVal": "59",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "11",
      "iftrue": "2",
      "iftrueVal": "63",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "12",
      "iftrue": "2",
      "iftrueVal": "67",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "13",
      "iftrue": "2",
      "iftrueVal": "71",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "14",
      "iftrue": "2",
      "iftrueVal": "75",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "15",
      "iftrue": "2",
      "iftrueVal": "79",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "16",
      "iftrue": "2",
      "iftrueVal": "83",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "17",
      "iftrue": "2",
      "iftrueVal": "87",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "18",
      "iftrue": "2",
      "iftrueVal": "91",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "19",
      "iftrue": "2",
      "iftrueVal": "95",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "answer",
      "comparison": "1",
      "value": "20",
      "iftrue": "2",
      "iftrueVal": "99",
      "iffalse": "1",
      "iffalseVal": "",
      "name": "Check Variable"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed1",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed1",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ : Comme je vois, oui",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed1",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed2",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed2",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ : Redemandez plus tard",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed2",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed3",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed3",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ : Mieux vaut ne pas le dire maintenant",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed3",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed4",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed4",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ : Peut pas prédire maintenant",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed4",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed5",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed5",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ : Concentrez-vous et redemandez",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed5",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed6",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed6",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ : Ne comptez pas sur ça",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed6",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed7",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed7",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ : C'est certains",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed7",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed8",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed8",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ : Il en est décidément ainsi",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed8",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed9",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed9",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ : Probablement",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed9",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed10",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed10",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ : Ma réponse est non",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed10",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed11",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed11",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ : Mes sources disent non",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed11",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed12",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed12",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ : Les perspectives sont pas si bonnes",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed12",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed13",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed13",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ : Les perspectives sont bonnes",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed13",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed14",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed14",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ Réponse flou, réessayez",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed14",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed15",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed15",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ Les signes pointent vers \"oui\"",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed15",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed16",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed16",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ Très douteusement",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed16",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed17",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed17",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ Sans doutes",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed17",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed18",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed18",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ Oui",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed18",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed19",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed19",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ Oui, définitivement",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed19",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "title": "🔮 8Ball",
      "author": "",
      "color": "#4c3a6e",
      "url": "",
      "authorIcon": "",
      "authorUrl": "",
      "imageUrl": "",
      "thumbUrl": "",
      "timestamp": "false",
      "debug": "false",
      "text": "",
      "year": "",
      "month": "",
      "day": "",
      "hour": "",
      "minute": "",
      "second": "",
      "storage": "1",
      "varName": "embed20",
      "name": "Create Embed Message"
    },
    {
      "storage": "1",
      "varName": "embed20",
      "message": "__Question__ : ${tempVars(\"question\")}\n__Réponse__ Vous pouvez y répondre",
      "name": "Set Embed Description"
    },
    {
      "storage": "1",
      "varName": "embed20",
      "channel": "0",
      "varName2": "",
      "storage3": "0",
      "varName3": "",
      "iffalse": "0",
      "iffalseVal": "",
      "messageContent": "",
      "name": "Send Embed Message"
    }
  ],
  "customData": {
    "Command Info": {
      "category": "Ownership",
      "description": "Coming Soon!",
      "include": "Yes"
    }
  }
}
